version: '3'
services:
  webapp:
    image: razeware/dockerized
    ports:
      - "80:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data/acronyms
